alert ("wag mo ibaback hindi to virus i click mo lang yung 'ok' goods na😎")
alert ("Hello")
alert ("malapit na pasko")
alert ("ehem baka naman")
alert ("namamasko lang")
alert ("kahit 100 pataas lang okay na sakin")
alert ("pambili lang ng gusto ko")
alert ("bibili kasi ako Lamborghini")
alert ("alam ko naman may mabuti kang puso")
alert ("kahit gcash nalang")
alert ("maging masaya sana pasko mo")
alert ("yun lang")
alert ("😘")